version: '3'

services:
  php:
    build: ./config/php
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
  
  apache:
    build: ./config/apache
    depends_on:
      - php
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html