SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `example` DEFAULT CHARACTER SET utf8;
USE `example`;

DROP TABLE IF EXISTS `example`.`button_presses`;
CREATE TABLE `example`.`button_presses` (
  `button_press_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `button_pressed_at` date NOT NULL,
  PRIMARY KEY (`button_press_id`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;